version: '3.1'
services: 
  mongohost:
    image: mongo:7
    restart: always
    container_name: mongodb
    volumes: 
      - ./data:/data/db
    ports:
    - 27017:27017

  rest-api:
    build: .
    restart: always
    container_name: restapi
    ports:
     - 5000:5106
    depends_on:
      - mongohost
